Traceback (most recent call last):
  File "main.py", line 101, in <module>
    myStream.filter(track=tracking)
  File "/home/kryczko/anaconda/envs/py3k/lib/python3.3/site-packages/tweepy/streaming.py", line 430, in filter
    self._start(async)
  File "/home/kryczko/anaconda/envs/py3k/lib/python3.3/site-packages/tweepy/streaming.py", line 346, in _start
    self._run()
  File "/home/kryczko/anaconda/envs/py3k/lib/python3.3/site-packages/tweepy/streaming.py", line 286, in _run
    raise exception
  File "/home/kryczko/anaconda/envs/py3k/lib/python3.3/site-packages/tweepy/streaming.py", line 255, in _run
    self._read_loop(resp)
  File "/home/kryczko/anaconda/envs/py3k/lib/python3.3/site-packages/tweepy/streaming.py", line 307, in _read_loop
    next_status_obj = buf.read_len(length)
  File "/home/kryczko/anaconda/envs/py3k/lib/python3.3/site-packages/tweepy/streaming.py", line 161, in read_len
    self._buffer += self._stream.read(read_len)
TypeError: Can't convert 'bytes' object to str implicitly
